version:
  name: velociraptor
  version: 0.75.6
  commit: 0e657d636
  build_time: "2025-12-29T14:15:51Z"
  compiler: go1.25.0
  system: linux
  architecture: amd64
Client:
  server_urls:
  - https://velociraptor.lab:8000/
  ca_certificate: |
    -----BEGIN CERTIFICATE-----
    MIIDSzCCAjOgAwIBAgIQb3d3jTyRHHK/iabH6HGjFzANBgkqhkiG9w0BAQsFADAa
    MRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwHhcNMjYwMTA4MTUwODM3WhcNMzYw
    MTA2MTUwODM3WjAaMRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwggEiMA0GCSqG
    SIb3DQEBAQUAA4IBDwAwggEKAoIBAQCvgzkrBVB3IVMf+2Iur82TU/Rj7UiDllA7
    J++nSszlYjTHIfWFgPJAv0fDa/xJnafLG9IwjjmCoi5Cjkzs34HNjBF2r/supRRG
    MhV61APlrIN4mRsRvs9guZxWVLaBZG4Z1aeU2Yev5dr2/8Kb3Yj8xK2x0bjUhR7L
    V7oKB85bJvFhh6UKEgeaj6JXtsQEmONofTIRBsRf8MDjSTdauB7X0AfqlaS951nq
    qwxaR+1Zm99jDFX2nAbKMyU3eT66KncXkKmfD2/3hPclJD181ItUyR0UxCPRIq13
    IzDl32zaeFt8Eu59tyiroizhHG8tvYa3tSUM1LpatIHad0FCMzU/AgMBAAGjgYww
    gYkwDgYDVR0PAQH/BAQDAgKkMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcD
    AjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBTDIz0eaPU+Bgq+KjEhUEIc5la+
    ODAoBgNVHREEITAfgh1WZWxvY2lyYXB0b3JfY2EudmVsb2NpZGV4LmNvbTANBgkq
    hkiG9w0BAQsFAAOCAQEAiWACdAZRV2GFUEINRJgbE4uwopVKWsrPRUrrk9x3AZ4d
    t47hgKfgZ8yXSQvzmxHpSmTSS+iW8lH6RZNk563zX9iV+p/F6t85uz3uLRd52ZcR
    Mi1Q4Q22r8gNIqKpl3QfK+g8e0fIF73o5pJuKQfcmCApq7s/5792l+A/YLNNxgwj
    Dew24+ItBCNFSNe/XoNEIaRQVP/MddQ1hPVwlCrbx+DvXrkRjgEIiUwS904jVfuS
    rjFDG4HrTcp6PLBAAuMebRw/ucmCRAs7oV1QOf05DEwXL3TGYfdrOviTQ6sd+MlL
    1mEq3VkV0+CwzvFhrGW2SAwbnvzroC2KU2Kaw7xqTg==
    -----END CERTIFICATE-----
  nonce: TcTam8J0jTc=
  writeback_darwin: /etc/velociraptor.writeback.yaml
  writeback_linux: /etc/velociraptor.writeback.yaml
  writeback_windows: $ProgramFiles\Velociraptor\velociraptor.writeback.yaml
  level2_writeback_suffix: .bak
  tempdir_windows: $ProgramFiles\Velociraptor\Tools
  max_poll: 60
  nanny_max_connection_delay: 600
  windows_installer:
    service_name: Velociraptor
    install_path: $ProgramFiles\Velociraptor\Velociraptor.exe
    service_description: Velociraptor service
  darwin_installer:
    service_name: com.velocidex.velociraptor
    install_path: /usr/local/bin/velociraptor
  version:
    name: velociraptor
    version: 0.75.6
    commit: 0e657d636
    build_time: "2025-12-29T14:15:51Z"
    compiler: go1.25.0
    system: linux
    architecture: amd64
  server_version:
    version: 0.75.6
    commit: 0e657d636
    build_time: "2025-12-29T14:15:51Z"
  use_self_signed_ssl: true
  max_upload_size: 5242880
  local_buffer:
    memory_size: 52428800
    disk_size: 1073741824
    filename_linux: /var/tmp/Velociraptor_Buffer.bin
    filename_windows: $TEMP/Velociraptor_Buffer.bin
    filename_darwin: /var/tmp/Velociraptor_Buffer.bin
